### PR TITLE
Support for Chosen

### PR DESCRIPTION
**Pull request by mmariani**
This patch includes chosen 0.9.7 and two new widgets, that do not replace the standard ones.
No readonly templates or selenium tests are provided.

### CODE REVIEW

**Comment by dnouri** [comment]
Looks very nice.  Any chance we could get a Selenium test to go along with it?  :-)

**Comment by mmariani** [comment]
maybe, not today. this selenium thing is new to me :)

**Comment by dnouri** [comment]
OK let me know if you need any help.  There's instructions on how to set up Selenium and test the demo in the deformdemo package and in deform_bootstrap's README.

**Comment by mmariani** [comment]
I have added some tests now, though.. how am I supposed to check for the capture of an unordered set?
I also did not rebuild deform_bootstrap.css from less.

**Comment by dnouri** [comment]
I'm afraid I don't know what you're referring to.  Can you give a concrete example for your problem?

**Comment by mmariani** [comment]
self.assertSimilarRepr(captured, "{'countries': set(['EE', 'BG', 'IE'])}")

the results are not guaranteed to be in any specific order.

**Comment by dnouri** [comment]
You could eval it and compare:

```
>>> eval("{'countries': set(['EE', 'BG', 'IE'])}") == {'countries': set(['EE', 'BG', 'IE'])}
True
```

**Comment by mmariani** [comment]
ok, done

**Comment by dnouri** [comment]
Thanks a lot for this!

**Pull request merged**
