### PR TITLE
Typeahead remote source support

### PR DESCRIPTION
**Pull request by igudym**
Last Bootstrap supports typeahead remote source natively, now no need for additional plugin file. 
Also changed 'source' attribute name to 'values' to be real drop in replacement for deform's AutocompleteInputWidget

### CODE REVIEW

**Comment by dnouri** [comment]
Looks good but has two issues:
- It breaks the tests.  Tests need to be updated, and probably new ones added.  (I've added a commit on master that'll make it more obvious how to run the unit tests.  The instructions on how to run the Selenium tests are already there.  I'm sorry that testing this package is a bit involved...)
- It needs backward compatibility.  Passing a `source` argument should still work.  And a deprecation warning needs to be added to signal that `source` is going away.

It looks like `size` was never really used, was it?

**Comment by igudym** [comment]
Maybe I do something wrong, but when I run tests against head and  my pull request result is equal in both cases:
Ran 6 tests in 7.449s

FAILED (failures=2, errors=4)

Looks like tests was already broken.

About size I don't know. It referenced in template anyway.

**Comment by dnouri** [comment]
When I run tests on master I get this

```
$ bin/py.test
============================= test session starts ==============================
platform linux2 -- Python 2.7.3 -- pytest-2.3.3
plugins: cov
collected 5 items

deform_bootstrap/tests/test_config.py .
deform_bootstrap/tests/test_widget.py ....
--------------- coverage: platform linux2, python 2.7.3-final-0 ----------------
Name                        Stmts   Miss  Cover   Missing
---------------------------------------------------------
deform_bootstrap/__init__       8      0   100%   
deform_bootstrap/widget        72     32    56%   76-87, 91-108, 128-131, 134-138
---------------------------------------------------------
TOTAL                          80     32    60%   

=========================== 5 passed in 0.25 seconds ===========================
```

(I updated master just now again, but just to get a nicer test output.)

**Comment by igudym** [comment]
I broke something in my branch so that tests won't run. I restarted from fresh fork.

**Pull request closed without merging**
